source: .

exclude:
  - NO_GIT
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - bower.json
  - bower_components
  - gulpfile.js

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false
  toc_levels: 2..4
  # This is needed to disable builtin highlight-rouge
  syntax_highlighter: true

gems:
  - jekyll-compass
  - breakpoint

defaults:
  -
    scope:
      path: ''
    values:
      layout: layout

